---
title: "Homework 5"
author: "Eileen McGinnity"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(scales)
```


```{r load_data, message=FALSE, warning=FALSE}
homicides <- read_csv("../data/homicide-data.csv")
```

```{r baltimore}
baltimore_homicides <- homicides %>% 
  filter(city == "Baltimore") %>% 
  mutate(reported_date = ymd(reported_date),
         year = year(reported_date),
         month = month(reported_date))

baltimore_monthly_homicides <- baltimore_homicides %>% 
  group_by(month, year) %>% 
  count(name = "homicides")

baltimore_monthly_homicides <- baltimore_monthly_homicides %>% 
  mutate(date = paste(month, year, sep = "-")) %>% 
  mutate(date = my(date))

cold_months <- c(11, 12, 1, 2, 3, 4)

baltimore_monthly_homicides$season <- ifelse(baltimore_monthly_homicides$month %in% cold_months, "Winter", "Summer")

freddie_grey <- baltimore_homicides %>% 
  filter(victim_first == "FREDDIE CARLOS" & victim_last == "GREY")
```

```{r chart}
baltimore_monthly_homicides %>%
  ggplot(aes(x = date,
               y = homicides)) + 
  geom_col(aes(fill = season)) +
  geom_smooth(method = "loess", se = FALSE, span = 0.1) +
  theme_dark() +
  xlab("Date") +
  ylab("Monthly homicides") +
  ggtitle("Homicides in Baltimore, MD") +
  theme(legend.position = "bottom") +
  theme(legend.title = element_blank()) +
  scale_fill_manual(values = c(Winter = "lightblue", Summer = "lightgray")) +
  geom_vline(data = freddie_grey, aes(xintercept = reported_date), color = "red", linetype = "dashed", size = 1)
```


